#! /tmp/busybox sh

/tmp/busybox sed -i "s/SUPPORT_BIXBY>TRUE/SUPPORT_BIXBY>FALSE/g" /system_root/system/etc/floating_feature.xml
rm -rf /system_root/system/app/BixbyWakeup
rm -rf /system_root/system/app/VisionIntelligence3.7
rm -rf /system_root/system/priv-app/Bixby
rm -rf /system_root/system/priv-app/BixbyVisionFramework3.5
rm -rf /system_root/system/priv-app/SettingsBixby
