#! /tmp/busybox sh
rm -rf /system_root/system/priv-app/DeXonPC
rm -rf /system_root/system/priv-app/DesktopModeUiService
rm -rf /system_root/system/priv-app/KnoxDesktopLauncher
rm -rf /system_root/system/priv-app/DesktopSystemUI
